# Generated by Django 4.0.4 on 2022-05-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('usuario', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='produto_anunciado',
            field=models.ManyToManyField(blank=True, to='produto.anunciarproduto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='produto_comprado',
            field=models.ManyToManyField(blank=True, to='produto.produtocomprado'),
        ),
    ]
