# Generated by Django 4.0.4 on 2022-07-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnunciarProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Automóvel', 'Automóvel'), ('Eletrodoméstico', 'Eletrodoméstico'), ('Tecnologia', 'Tecnologia'), ('Alimento', 'Alimento'), ('Saúde', 'Saúde'), ('Vestuário', 'Vestuário'), ('Ferramenta', 'Ferramenta')], max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('data_anuncio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoComprado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ManyToManyField(to='produto.anunciarproduto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='imagens/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.anunciarproduto')),
            ],
        ),
    ]
