# Generated by Django 4.0.4 on 2022-05-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciarproduto',
            name='image',
            field=models.ImageField(default='online-shopping.png', upload_to='anuncios_pics'),
        ),
    ]
