# Generated by Django 4.0.4 on 2022-06-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_anunciarproduto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciarproduto',
            name='image',
            field=models.FileField(upload_to='anuncios_pics'),
        ),
    ]
